# -*- coding: utf-8 -*-
"""Tareas de Python Class

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17N7VewIYP5bumknKWM1lmsrbuAWUUTH1

##Curso de Programacion
#Semana 01 - Tarea

Resolver los siguientes ejercicios:

* José es administrador en una fábrica de chocolates, una de sus tareas es pedir las cajas al proveedor semanalmente, en cada caja entran 12 chocolates. Hacer un programa que le pida al jefe de producción la cantidad de chocolates que se producirán diariamente la próxima semana y resolver ¿qué debe hacer José?

* Dados los catetos de un triángulo rectángulo, calcular su hipotenusa.

* Escribir un programa que convierta un valor dado en grados Fahrenheit a grados Celsius. Recordar que la fórmula para la conversión es: C = (F-32)*5/9

* Escriba un programa que pida dos números enteros y que escriba si el mayor es múltiplo del menor.

* Mejore el programa anterior haciendo que no se acepten números negativos ni cero.

* Escriba un programa que pida un año y que escriba si es bisiesto o no. Se recuerda que los años bisiestos son múltiplos de 4, pero los múltiplos de 100 no lo son, aunque los múltiplos de 400 sí.

* Muestra los múltiplos de 3 a partir del 3 hasta el número que el usuario indique.

* Escriba un programa que pida dos números enteros. El programa pedirá de nuevo el segundo número mientras no sea mayor que el primero. El programa terminará escribiendo los dos números.

* Escriba un programa que pida números enteros mientras sean cada vez más grandes.

* Escriba un programa que pida las notas de un grupo, se le preguntará al usuario si quiere seguir ingresando notas, y mientras la respuesta sea Sí/SÍ/sí, se debe seguir ingresando. Al finalizar el ingreso de notas, se debe mostrar una lista de las notas aprobadas y otra de las desaprobadas.

* Pedir el nombre de 5 asignaturas y su notas respectivas, luego mostrar los mensajes: “En la asignatura XXXXXXX sacó XXXXXX, para cada asignatura.

* Un estacionamiento cobra S/3.00 por la primera hora, luego S/0.50 por cada hora siguiente. El cargo máximo por día es de S/12.00. Programe una función para que al ingresar el número de horas se imprima el cargo. Escriba una función que reciba dos números y determine si el primero es múltiplo del segundo. El usuario ingresará un número de horas, de minutos y segundos y nos devuelva el equivalente en segundos.
"""

## Resolucion de ejercicios ##

# Problema 1 #

chocolates_diarios =int(input("Ingresa la cantidad de chocolates diarios: "))
caja_chocolates = chocolates_diarios // 12
if chocolates_diarios % 12 != 0:
    caja_chocolates += 1
chocolates_semanal = caja_chocolates * 7
print("La cantidad de cajas de chocolates semanales es: ", chocolates_semanal)

# Problema 2 #

CatetoA = int(input("Ingrese el valor del cateto A: "))
CatetoB = int(input("Ingrese el valor del cateto B: "))
Ipotenusa = (CatetoA**2 + CatetoB**2)**0.5
print("La hipotenusa es: ", Ipotenusa)

# Problema 3 #

gradosf = float(input("Ingrese la temperatura en grados Fahrenheit: "))
gradosc = (gradosf - 32) * 5/9
print("La temperatura en grados Celsius es: ", gradosc)

# Problema 4 #

num1 = int(input("Ingrese el primer numero entero: "))
num2 = int(input("Ingrese el segundo numero entero: "))
if num1 % num2 == 0:
   print("El primer numero es multiplo del segundo")
else:
   print("El primer numero no es multiplo del segundo")

# Problema 5 #

num1 = int(input("Ingrese el primer numero entero: "))
num2 = int(input("Ingrese el segundo numero entero: "))

if num1 < 0 or num2 < 0:
    print("Los numeros no pueden ser negativos")
else:
    if num1 % num2 == 0:
        print("El primer numero es multiplo del segundo")
    else:
        print("El primer numero no es multiplo del segundo")

# Problema 6 #

year = int(input("Ingrese el año: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("El año es bisiesto")
else:
    print("El año no es bisiesto")

# Problema 7 #

mul = int(input("Ingrese las veces que quiere ver los multiplos de 3: "))
for i in range(3, mul+1, 3):
    print(i)

# Problema 8 #

numA = int(input("Escriba el primer numero: "))
numB = int(input("Escriba el segundo numero: "))
while (numB <= numA):
  print("El segundo número debe ser mayor que el primero.")
  numB = int(input("Escriba el segundo numero de nuevo: "))
print("El primer numero es: ", numA)
print("El segundo numero es: ", numB)

# Problema 9 #

num_principal = int(input("Ingrese el numero grande: "))
num_secundario = int(input("Ingrese su numero actual: "))

while True:
  if (num_secundario <= num_principal):
    print("El numero es menor al numero grande")
    break
  else:
    num_principal = num_secundario
    print("Numero grande actual: ",num_principal)
    num_secundario = int(input("Ingrese su numero actual: "))

# Problema 10 #

grupo = []
aprobados = []
desaprobados = []

while True:
  nota = int(input("Ingrese la nota del alumno: "))
  if nota >= 11:
    aprobados.append(nota)
  else:
    desaprobados.append(nota)

  respuesta = str(input("Desea ingresar otra nota? (S/N): "))
  if respuesta == "S" or respuesta == "s":
    continue
  else:
    break

print("Notas aprobadas:", aprobados)
print("Notas desaprobadas:", desaprobados)

# Problema 11 #

asignaturas = []
notasA = []

for i in range(5):
    asignatura = input("Ingresa el nombre de la asignatura: ")
    nota = float(input("Ingrese la nota: "))

    asignaturas.append(asignatura)
    notasA.append(nota)

for i in range(5):
    print(f"En la asignatura {asignaturas[i]} sacó {notasA[i]}")

# Problema 12 #

# Parte 1 #
horas = int(input("Ingrese la cantidad de horas: "))

if horas <= 1:
  cargo = 3.00
else:
  cargo = 3.00 + (horas - 1) * 0.50

if cargo > 12.00:
  cargo = 12.00

print("El cargo Total es: ", cargo)

# Parte 2 #

numb1 = int(input("Ingrese el primer numero: "))
numb2 = int(input("Ingrese el segundo numero: "))

if numb1 % numb2 == 0:
  print("El primer numero es multiplo del segundo")
else:
  print("El primer numero no es multiplo del segundo")

# Parte 3 #

hora = int(input("Ingrese la hora: "))
minuto = int(input("Ingrese los minutos: "))
segundo = int(input("Ingrese los segundos: "))

segundos = hora * 3600 + minuto * 60 + segundo

print("El equivalente en segundos es: ", segundos)